### ISSUE TITLE
Error when trying to delete rule

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#118]
```
backTrace

#0 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Core/Error.php(182): CRM_Core_Error::backtrace()
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /var/www/html/civirules/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /var/www/html/civirules/sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: constraint violation", -3, 16, (Array:2), "DELETE FROM civirule_rule  WHERE (  civirule_rule.id = 4 )  [nativecode=1451 ...")
#4 /var/www/html/civirules/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-3, 16, (Array:2), "DELETE FROM civirule_rule  WHERE (  civirule_rule.id = 4 )  [nativecode=1451 ...")
#5 /var/www/html/civirules/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -3, NULL, NULL, "DELETE FROM civirule_rule  WHERE (  civirule_rule.id = 4 )  [nativecode=1451 ...", "DB_Error", TRUE)
#6 /var/www/html/civirules/sites/all/modules/civicrm/packages/DB/mysql.php(895): DB_common->raiseError(-3, NULL, NULL, NULL, "1451 ** Cannot delete or update a parent row: a foreign key constraint fails ...")
#7 /var/www/html/civirules/sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
#8 /var/www/html/civirules/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("DELETE FROM civirule_rule  WHERE (  civirule_rule.id = 4 ) ")
#9 /var/www/html/civirules/sites/all/modules/civicrm/packages/DB/DataObject.php(2442): DB_common->query("DELETE FROM civirule_rule  WHERE (  civirule_rule.id = 4 ) ")
#10 /var/www/html/civirules/sites/all/modules/civicrm/packages/DB/DataObject.php(1456): DB_DataObject->_query("DELETE FROM civirule_rule  WHERE (  civirule_rule.id = 4 ) ")
#11 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Core/DAO.php(480): DB_DataObject->delete(FALSE)
#12 /var/www/html/civirules/sites/all/modules/civi_ext/org.civicoop.civirules/CRM/Civirules/BAO/Rule.php(107): CRM_Core_DAO->delete()
#13 /var/www/html/civirules/sites/all/modules/civi_ext/org.civicoop.civirules/CRM/Civirules/Form/Rule.php(124): CRM_Civirules_BAO_Rule::deleteWithId("4")
#14 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Core/Form.php(345): CRM_Civirules_Form_Rule->postProcess()
#15 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Core/StateMachine.php(164): CRM_Core_Form->mainProcess()
#16 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Civirules_Form_Rule), "next", "Next")
#17 /var/www/html/civirules/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Civirules_Form_Rule), "next")
#18 /var/www/html/civirules/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Civirules_Form_Rule), "next")
#19 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("next")
#20 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(115): CRM_Core_Controller->run()
#21 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Core/Invoke.php(286): CRM_Utils_Wrapper->run("CRM_Civirules_Form_Rule", "Rule", NULL)
#22 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))
#23 /var/www/html/civirules/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:4))
#24 /var/www/html/civirules/sites/all/modules/civicrm/drupal/civicrm.module(482): CRM_Core_Invoke::invoke((Array:4))
#25 [internal function](): civicrm_invoke("civirule", "form", "rule")
#26 /var/www/html/civirules/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))
#27 /var/www/html/civirules/index.php(21): menu_execute_active_handler()
#28 {main}

```

**Comment by ErikHommel** [comment]
Solved in current version, can not replicate

**Comment by ErikHommel** [comment]
Appears again in CiviRules 1.13
