### ISSUE TITLE
Can't edit a rule whose CiviruleAction references a deleted group

### ISSUE THREAD

**Issue by MegaphoneJon** [CiviCooP/org.civicoop.civirules#172]
I have a CiviRule that adds contacts to a particular group.  If you delete the group, you can no longer edit the CiviRule (backtrace follows).

I'd work on a patch, but I'm not sure what the best approach here.  We could wrap the `getvalue` calls in a try...catch block - but then what?  We can use `get` instead so we can ignore empty values, but I'm not sure if we'll need to do this in several places.  Ideally we remove those groups from the rule, but that sounds tricky here.

```
#0 /path/to/drupalroot/sites/default/files/civicrm/ext/org.civicoop.civirules/CRM/CivirulesActions/GroupContact/GroupContact.php(82): civicrm_api3("Group", "getvalue", (Array:2))
#1 /path/to/drupalroot/sites/default/files/civicrm/ext/org.civicoop.civirules/CRM/Civirules/Form/Rule.php(387): CRM_CivirulesActions_GroupContact_GroupContact->userFriendlyConditionParams()
#2 /path/to/drupalroot/sites/default/files/civicrm/ext/org.civicoop.civirules/CRM/Civirules/Form/Rule.php(282): CRM_Civirules_Form_Rule->getRuleActions()
#3 /path/to/drupalroot/sites/default/files/civicrm/ext/org.civicoop.civirules/CRM/Civirules/Form/Rule.php(258): CRM_Civirules_Form_Rule->createUpdateFormElements()
#4 /path/to/drupalroot/sites/default/files/civicrm/ext/org.civicoop.civirules/CRM/Civirules/Form/Rule.php(34): CRM_Civirules_Form_Rule->createFormElements()
#5 /path/to/drupalroot/sites/all/modules/civicrm/CRM/Core/Form.php(564): CRM_Civirules_Form_Rule->buildQuickForm()
#6 /path/to/drupalroot/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php(92): CRM_Core_Form->buildForm()
#7 /path/to/drupalroot/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Civirules_Form_Rule), "display")
#8 /path/to/drupalroot/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Civirules_Form_Rule), "display")
#9 /path/to/drupalroot/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("display")
#10 /path/to/drupalroot/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(113): CRM_Core_Controller->run()
#11 /path/to/drupalroot/sites/all/modules/civicrm/CRM/Core/Invoke.php(283): CRM_Utils_Wrapper->run("CRM_Civirules_Form_Rule", "Rule", NULL)
#12 /path/to/drupalroot/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))
#13 /path/to/drupalroot/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#14 /path/to/drupalroot/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:4))
#15 [internal function](): civicrm_invoke("civirule", "form", "rule")
#16 /path/to/drupalroot/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))
#17 /path/to/drupalroot/index.php(21): menu_execute_active_handler()
#18 {main}

Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
Expected one Group but found 0

Return to home page.
```

**Comment by jaapjansma** [comment]
I would say use a try catch on the getvalue api
